version: '3.8'

services: 
  users-db:
    build:
      context: ./DB
      dockerfile: dockerfile-mysql-users
    networks:
      - net
    volumes: 
      - users_vol:/var/lib/mysql
    container_name: users_db_container

  data-db:
    build:
      context: ./DB
      dockerfile: dockerfile-mysql-data
    networks:
      - net
    volumes: 
      - data_vol:/var/lib/mysql
    container_name: data_db_container

  db-client: # per il testing
    build:
      context: ./DB
      dockerfile: dockerfile-mysql-users-client
    depends_on:
      - users-db
      - data-db
    networks:
      - net
    container_name: db_client_container
    stdin_open: true  # Mantiene lo stdin aperto per una shell interattiva

  data-collector:
    build:
      context: ./DataCollector
      dockerfile: dockerfile-datacollector
    depends_on:
      - users-db
      - data-db
    networks:
      - net
    container_name: data_collector

networks:
  net:
    driver: bridge

volumes:
  users_vol: 
    driver: local
  data_vol:
    driver: local

