version: '3.8'

services:
  db:
    build:
      context: ./DB
      dockerfile: dockerfile-mysql
    networks:
      - net1
      - net2
    volumes:
      - db_vol:/var/lib/mysql
    container_name: mysql-container

  server-grpc:
    build:
      context: .
      dockerfile: gRPC/dockerfile-server
    depends_on:
      - db
    networks:
      - net1
    container_name: grpc-server-service
    ports:
      - "50051:50051"
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper-service
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - net2
    restart: always

  
  ###### 3 broker di Kafka ######
  kafka-broker-1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-broker-1-service
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-service:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-1-service:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    networks:
      - net2
    restart: always
    volumes:
      - kafka_broker_1_data:/var/lib/kafka/data

  kafka-broker-2:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-broker-2-service
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-service:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-2-service:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_LISTENER_NAME: PLAINTEXT  
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    networks:
      - net2
    restart: always
    volumes:
      - kafka_broker_2_data:/var/lib/kafka/data

  kafka-broker-3:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-broker-3-service
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-service:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-3-service:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    networks:
      - net2
    restart: always
    volumes:
      - kafka_broker_3_data:/var/lib/kafka/data
    
  ####### ADMIN KAFKA (creazione topic e monitoraggio) #######
  kafka-admin:
    build:
      context: ./KafkaAdmin
      dockerfile: dockerfile-kafka-admin
    container_name: kafka-admin-container
    depends_on:
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3
    networks:
      - net2
    restart: always
    
  ###### produttori e consumatori kafka ######
  data-collector:
    build:
      context: .
      dockerfile: DataCollector/dockerfile-datacollector
    depends_on:
      - db
      - kafka-admin
    networks:
      - net2
    container_name: data-collector-service
    restart: always

  alert-system:
    build:
      context: .
      dockerfile: AlertSystem/dockerfile-alertsystem
    depends_on:
      - kafka-admin
      - db
    networks:
      - net2
    container_name: alert_system_container
    restart: always

  alert-notifier-system:
    build:
      context: .
      dockerfile: AlertNotifierSystem/dockerfile-notifier
    depends_on:
      - kafka-admin
    networks:
      - net2
    container_name: alert_notifier_container
    restart: always


  ################## PROMETHEUS ##########################
  prometheus:
    build:
      context: ./Prometheus
      dockerfile: dockerfile-prometheus
    networks:
      - net2
    volumes:
      - prometheus-data:/prometheus  # Volume persistente per i dati di Prometheus
    container_name: prometheus-service
    ports: 
      - 53120:9090



networks:
  net1:
    driver: bridge
  net2:
    driver: bridge

volumes:
  db_vol:
    driver: local
  kafka_broker_1_data:
    driver: local
  kafka_broker_2_data:
    driver: local
  kafka_broker_3_data:
    driver: local
  prometheus-data:
    driver: local