version: '3.8'

services: 
  db:
    build:
      context: ./DB
      dockerfile: dockerfile-mysql
    networks:
      - net1
      - net2
    volumes: 
      - db_vol:/var/lib/mysql
    container_name: mysql_container

  data-collector:
    build:
      context: ./DataCollector
      dockerfile: dockerfile-datacollector
    depends_on:
      - db
    networks:
      - net2
    container_name: data_collector
    restart: always
    
  server-grpc:
    build:
      context: ./gRPC
      dockerfile: dockerfile-server
    depends_on:
      - db
    networks:
      - net1
    container_name: server
    ports:
      - "50051:50051"
    restart: always

networks:
  net1:
    driver: bridge
  net2: 
    driver: bridge
volumes:
  db_vol: 
    driver: local