version: '3.8'

services: 
  db:
    build:
      context: ./DB
      dockerfile: dockerfile-mysql
    networks:
      - net
    volumes: 
      - db_vol:/var/lib/mysql
    container_name: mysql_container

  data-collector:
    build:
      context: ./DataCollector
      dockerfile: dockerfile-datacollector
    depends_on:
      - db
    networks:
      - net
    container_name: data_collector
    restart: always

  server-grpc:
    build:
      context: ./gRPC
      dockerfile: dockerfile-server
    depends_on:
      - db
    networks:
      - net
    container_name: server
    ports:
      - "50051:50051"

networks:
  net:
    driver: bridge

volumes:
  db_vol: 
    driver: local