FROM python:3.9  

WORKDIR /app

# TODO: vedere che dipendenze servono e aggiungerle opportunamente
RUN pip install pymysql

RUN pip install bcrypt pymysql

RUN pip install cryptography

COPY DB/db_config.py /app/
COPY AlertSystem/alert_system.py /app/

# CMD [ "python", "alert_system.py"]