FROM python:3.9

WORKDIR /app

COPY DataCollector/requirements.txt .

RUN pip install -r requirements.txt

COPY DataCollector/data_collector.py .
COPY DataCollector/circuit_breaker.py .
COPY CQRS/command_service.py .
COPY CQRS/query_service.py .
COPY DB/db_config.py .

CMD ["python", "data_collector.py"]