FROM python:3.9

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY DataCollector/data_collector.py /app/
COPY DataCollector/circuit_breaker.py /app/
COPY DB/db_config.py /app/

CMD ["python", "data_collector.py"]