log_level: debug

global:
  resolve_timeout: 10m
  http_config:
    tls_config:
      insecure_skip_verify: true

route:  # ogni avviso generato da Prometheus viene confrontato con le regole definite nella route per determinare quale receiver deve gestirlo.
  receiver: "email-notifications" # tutti gli avvisi verranno inviati al receiver chiamato 'pager'
  repeat_interval: 3h

receivers:
    - name: 'email-notifications'
      email_configs:
      - to: "test-esame@mailo.com"
        from: "alertmanager@mailo.com"
        smarthost: "smtp.mailo.com:587"
        auth_password: "Progetto0921"
        auth_username: "alertmanager@mailo.com" 