# Kafka PersistentVolume e PersistentVolumeClaim per Broker 1, 2, 3
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-broker-1-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data/kafka/broker-1

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-broker-1-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-broker-2-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data/kafka/broker-2

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-broker-2-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-broker-3-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data/kafka/broker-3

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-broker-3-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi

---

# Kafka Brokers Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker-1
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker-1
  template:
    metadata:
      labels:
        app: kafka-broker-1
    spec:
      containers:
        - name: kafka-broker-1
          image: confluentinc/cp-kafka:latest
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL
              value: "PLAINTEXT"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-broker-1:9092"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092"
            - name: KAFKA_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "3"
          volumeMounts:
            - name: kafka-broker-1-data
              mountPath: /var/lib/kafka/data
      volumes:
        - name: kafka-broker-1-data
          persistentVolumeClaim:
            claimName: kafka-broker-1-pvc

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker-2
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker-2
  template:
    metadata:
      labels:
        app: kafka-broker-2
    spec:
      containers:
        - name: kafka-broker-2
          image: confluentinc/cp-kafka:latest
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "2"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL
              value: "PLAINTEXT"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-broker-2:9092"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092"
            - name: KAFKA_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "3"
          volumeMounts:
            - name: kafka-broker-2-data
              mountPath: /var/lib/kafka/data
      volumes:
        - name: kafka-broker-2-data
          persistentVolumeClaim:
            claimName: kafka-broker-2-pvc

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker-3
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker-3
  template:
    metadata:
      labels:
        app: kafka-broker-3
    spec:
      containers:
        - name: kafka-broker-3
          image: confluentinc/cp-kafka:latest
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "3"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL
              value: "PLAINTEXT"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-broker-3:9092"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092"
            - name: KAFKA_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "3"
          volumeMounts:
            - name: kafka-broker-3-data
              mountPath: /var/lib/kafka/data
      volumes:
        - name: kafka-broker-3-data
          persistentVolumeClaim:
            claimName: kafka-broker-3-pvc

---

# Kafka Broker Services
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-1-service
spec:
  ports:
    - port: 9092
      targetPort: 9092
  selector:
    app: kafka-broker-1

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-2-service
spec:
  ports:
    - port: 9092
      targetPort: 9092
  selector:
    app: kafka-broker-2

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-3-service
spec:
  ports:
    - port: 9092
      targetPort: 9092
  selector:
    app: kafka-broker-3