# DataCollector Deployment
apiVersion: apps/v1
kind: Deployment

metadata: 
  name: data-collector-deployment
  labels:
    app: data-collector

spec:
  replicas: 1
  selector:
    matchLabels: 
      app: data-collector
  template: 
    metadata:
      labels:
        app: data-collector
    spec:
      containers:
        - name: data-collector-container
          image: mygiuseppe09/data-collector-image:v1
      initContainers:
        - name: init-container
          image: busybox
          command:
            - "sh"
            - "-c"
            - |
              # Tentativo di connessione ai 3 Kafka brokers. Si esegue fino a che non si connette ad uno di essi
              for broker in "kafka-broker-1-service:9092" "kafka-broker-2-service:9092" "kafka-broker-3-service:9092"; do
                echo "Trying to connect to $broker..."
                until nc -zv $broker; do
                  echo "Waiting for $broker to be available..."
                  sleep 2
                done
                echo "$broker is now available!"
                break
              done
          ports:
            - containerPort: 9999 # La porta su cui il data-collector espone le metriche 

---
apiVersion: v1
kind: Service
metadata:
  name: data-collector-service
spec:
  selector:
    app: data-collector
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9999