apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Permette l'accesso in lettura e scrittura a un solo nodo
  resources:
    requests:
      storage: 5Gi  # Dimensione dello spazio richiesto
