
apiVersion: apps/v1
kind: Deployment

metadata: # qui indichiamo i nomi e i labels associati al'oggetto Deploy
  name: server-deployment
  labels:
    app: server

spec: 
  replicas: 1
  selector: # sotto vi sono i POD che verranno gestiti dal Deployment
    matchLabels: 
      app: server
  template: # modello a partire dal quale vengono creati i POD
    metadata: 
      labels:
        app: server
    spec: 
      initContainers:
        - name: init-container
          image: busybox
          command: ['sh', '-c', 'until nc -zv mysql-container 3306; do echo "Waiting for zookeeper..."; sleep 2; done']
      containers:
        - name: grpc-server-container
          image: alberto2106/server-grpc:v1
          ports:
            - containerPort: 50051


---
apiVersion: v1
kind: Service

metadata:
  name: grpc-server-service
  labels:
    app: server

spec:
  type: NodePort
  selector: # Si abbina ai Pod usando le stesse label del Deployment
    app: server
  ports:
    - name: grpc-port 
      protocol: TCP
      port: 50051       # Porta del service (internamente visibile ai client)
      targetPort: 50051 # Porta dal container del Pod
      nodePort: 30051   # Porta del nodo (esterna al cluster)