FROM python:3.9  

WORKDIR /app

RUN pip install grpcio==1.68.0 grpcio-tools==1.68.0

RUN pip install pymysql

RUN pip install bcrypt pymysql

RUN pip install cryptography


COPY gRPC/usermanagement_pb2.py gRPC/usermanagement_pb2_grpc.py gRPC/server.py /app/
COPY CQRS/command_service.py .
COPY CQRS/query_service.py .
COPY DB/db_config.py .



CMD [ "python", "server.py"]