FROM python:3.9  

WORKDIR /app

RUN pip install pymysql
RUN pip install bcrypt pymysql
RUN pip install cryptography
RUN pip install confluent_kafka

COPY notifier.py .
COPY email_config.py .


CMD [ "python", "notifier.py"]